spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      location: C:/convenient/product
      uploadPath: file:///C:/convenient/

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #        globally_quoted_identifiers: true

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:cvsreviewproject
  sql:
    init:
      data-locations: classpath*:data.sql
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 360