spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #        globally_quoted_identifiers: true

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:cvsreviewproject
  sql:
    init:
      data-locations: classpath*:data.sql
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    converters:
      preferred-json-mapper: gson
#jwt:
#  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

#  security:
#    user:
#      username: user
#      password: imyonghan


mail:
  address:
    admin: admin@gmail.com
jwt:
  key: kevin123412341234123412341234123412341234123412341234
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
